remote_theme: "mmistakes/minimal-mistakes@master"
minimal_mistakes_skin: "air"

# ----------------------------------------
# ▶️ Site Settings
# ----------------------------------------
title: "Hojun Choi's Portfolio"
subtitle: "Data Scientist in Progress"
name: &name "Hojun Choi"
description: &description "Learning, building, and writing in data science and computer vision."
url: "https://hojjang98.github.io"
baseurl: ""
repository: "hojjang98/hojjang98.github.io"
teaser: "/assets/images/teaser.png"

# ----------------------------------------
# 🧑 Author
# ----------------------------------------
author:
  name: *name
  avatar: "/assets/images/hj.jpeg"
  bio: "Aspiring Data Scientist | CV | ML | Python"
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hojjang98"
    - label: "Portfolio"
      icon: "fas fa-fw fa-id-card"
      url: "https://hojjang98.github.io"

# ----------------------------------------
# 🌐 SEO & Social
# ----------------------------------------
twitter:
  username: "hojjang98"
og_image: "/assets/images/site-logo.png"

social:
  type: "Person"
  name: "Hojun Choi"
  links:
    - "https://github.com/hojjang98"

# ----------------------------------------
# 🔍 Search & Analytics
# ----------------------------------------
search: true
search_full_content: true
analytics:
  provider: false

# ----------------------------------------
# 💬 Comments (off)
# ----------------------------------------
comments:
  provider: false

# ----------------------------------------
# 🧱 Layout Defaults
# ----------------------------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# ----------------------------------------
# 🔎 Plugins
# ----------------------------------------
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

# ----------------------------------------
# 🕐 Time & Markdown
# ----------------------------------------
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Asia/Seoul

# ----------------------------------------
# 📁 Collections (for custom categories)
# ----------------------------------------
collections:
  posts:
    output: true
    permalink: /:categories/:title/
  portfolio:
    output: true
    permalink: /:collection/:path/

# ----------------------------------------
# 📂 Include/Exclude
# ----------------------------------------
include:
  - _pages
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# ----------------------------------------
# 🔧 SASS & Build
# ----------------------------------------
sass:
  sass_dir: _sass
  style: compressed


# _config.yml
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

# MathJax enable
mathjax: true
