title: "Hojun Choi's Blog"
description: "A space to share my growth, learning, and data science journey"
theme: minima

# Blog settings
show_excerpts: true
markdown: kramdown
paginate: 5

# Navigation menu
header_pages:
  - index.md
  - about.md
